### PR TITLE
Thin CC download fix

### PR DESCRIPTION
**Pull request by SteelWagstaff**
The thin CC download action was causing conflicts with other plugins we
have, so created a more specific name for the button/action to produce
disambiguation.

### CODE REVIEW

**Comment by bracken** [comment]
Great, thanks. We should be able to get to this sometime this week.

**Comment by monkecheese** [comment]
Hi @SteelWagstaff,

I'm testing your fix, and the download seems to work fine.  However, the changes you implemented appear to present a new bug in the Thin-CC Preview.  The error reads as follows:

`Warning: get_resource_type() expects parameter 1 to be resource, string given in /Sites/candela/wp-content/plugins/candela-thin-exports/cc/manifest.php on line 75`

To reproduce this error, try navigating in the "Admin Area" to "Tools" -> "Export to ThinCC" and click on the "Preview Thin-CC" button.

Are you able to reproduce that error?

Thanks for your help.

**Comment by SteelWagstaff** [comment]
Hi Bryan,

I don’t see that error message myself, no. I’ve tried clicking the "preview thin-cc” button with a few different check box possibilities selected, and none of them triggers the error you described (or any other error message for that matter).

Best,

Steel Wagstaff<http://steelwagstaff.com>
Instructional Technology Consultant
L&S Learning Support Services, UW-Madison
275 Van Hise Hall || 608.262.0515 || swagstaff@wisc.edu<mailto:swagstaff@wisc.edu>



On Apr 18, 2016, at 3:08 PM, Bryan Borgeson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @SteelWagstaff<https://github.com/SteelWagstaff>,

I'm testing your fix, and the download seems to work fine. However, the changes you implemented appear to present a new bug in the Thin-CC Preview. The error reads as follows:

Warning: get_resource_type() expects parameter 1 to be resource, string given in /Sites/candela/wp-content/plugins/candela-thin-exports/cc/manifest.php on line 75

To reproduce this error, try navigating in the "Admin Area" to "Tools" -> "Export to ThinCC" and click on the "Preview Thin-CC" button.

Are you able to reproduce that error?

Thanks for your help.

**Comment by bracken** [comment]
It wasn't working for me either, there was a javascript file than needed updating too, I made the change and merged it: https://github.com/lumenlearning/candela/commit/49e707e5cb5acb06f1f4349df0590d397574228e

**Pull request closed without merging**
