### PR TITLE
Add 'Candela Outcomes' module for outcomes meta field

### PR DESCRIPTION
**Pull request by kdv24**
(including validation)

### CODE REVIEW

**Comment by jgraham909** [comment]
FYI there was already some work regarding outcomes in the outcomes branch. I'm not sure if its still useful;  
https://github.com/lumenlearning/candela/tree/outcomes?files=1

**Comment by jgraham909** [comment]
https://github.com/lumenlearning/candela/tree/outcomes/wp-content/plugins/candela-outcomes

**Comment by bracken** [comment]
It looks like your .htaccess changes got pushed up again. Could you fix that? Other than that it looks good though.

**Comment by bracken** [comment]
@jgraham909, yeah, we ended up going a different direction and moving most of the outcomes functionality out of candela. So now a post will just references a GUID instead of candela owning the whole infrastructure of outcomes.

**Pull request merged**
